name: Create Release
on: 
  push:
    tags:
    - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'RelayRelease.zip'
        path: './_Release'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
       artifacts: "RelayRelease.zip"
       token: ${{ secrets.GITHUB_TOKEN }}
