on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
name: Upload Release Asset

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Archive Release
    - uses: actions/checkout@v2
    - uses: vimtor/action-zip@v1
      with:
          files: ./_Release/Revit2022
          dest: Relay.zip
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            Relay.zip
