name: Create Release
on: 
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'v*')
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'RelayRelease.zip'
        path: './_Release'
    - name: Upload Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            RelayRelease.zip
